environment: dev

storage:
  account_name: "stadevtfmtraficomadrid"
  containers:
    landing: landing
    bronze: bronze
    silver: silver
    gold: gold

catalogs:
  bronze: dev_bronze
  silver: dev_silver
  gold: dev_gold

paths:
  checkpoint_dir: "_checkpoint"
  schema_location_mode: "same_as_checkpoint"

runtime:
  default_trigger: available_now
  log_level: INFO
  diagnostic_counts: false
